# Generated by Django 2.1.5 on 2019-01-14 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=120)),
                ('aciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DersKayit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 11, 24, 38, 227190))),
                ('bitis', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 11, 24, 38, 227217))),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Ders')),
            ],
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=120)),
                ('aciklama', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='derskayit',
            name='sinif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Sinif'),
        ),
    ]
